/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBottomNav: typeof import('./src/components/AppBottomNav.vue')['default']
    BudgetDrawer: typeof import('./src/components/BudgetDrawer.vue')['default']
    Button: typeof import('./src/components/ui/button/Button.vue')['default']
    Card: typeof import('./src/components/ui/card/Card.vue')['default']
    CardContent: typeof import('./src/components/ui/card/CardContent.vue')['default']
    CardHeader: typeof import('./src/components/ui/card/CardHeader.vue')['default']
    CardTitle: typeof import('./src/components/ui/card/CardTitle.vue')['default']
    CategoryDrawer: typeof import('./src/components/CategoryDrawer.vue')['default']
    DashboardHeader: typeof import('./src/components/DashboardHeader.vue')['default']
    Drawer: typeof import('./src/components/ui/drawer/Drawer.vue')['default']
    DrawerContent: typeof import('./src/components/ui/drawer/DrawerContent.vue')['default']
    DrawerFooter: typeof import('./src/components/ui/drawer/DrawerFooter.vue')['default']
    DrawerHeader: typeof import('./src/components/ui/drawer/DrawerHeader.vue')['default']
    DrawerTitle: typeof import('./src/components/ui/drawer/DrawerTitle.vue')['default']
    DrawerTrigger: typeof import('./src/components/ui/drawer/DrawerTrigger.vue')['default']
    ExpenseCalendar: typeof import('./src/components/ExpenseCalendar.vue')['default']
    Input: typeof import('./src/components/ui/input/Input.vue')['default']
    Label: typeof import('./src/components/ui/label/Label.vue')['default']
    LedgerBottomNav: typeof import('./src/components/LedgerBottomNav.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('./src/components/ui/select/Select.vue')['default']
    StatsView: typeof import('./src/components/StatsView.vue')['default']
    TheCounter: typeof import('./src/components/TheCounter.vue')['default']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
    TheInput: typeof import('./src/components/TheInput.vue')['default']
    TransactionDrawer: typeof import('./src/components/TransactionDrawer.vue')['default']
    TransactionsList: typeof import('./src/components/TransactionsList.vue')['default']
  }
}
