/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...all]': RouteRecordInfo<'/[...all]', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/hi/[name]': RouteRecordInfo<'/hi/[name]', '/hi/:name', { name: ParamValue<true> }, { name: ParamValue<false> }>,
    '/history': RouteRecordInfo<'/history', '/history', Record<never, never>, Record<never, never>>,
    '/invite/[id]': RouteRecordInfo<'/invite/[id]', '/invite/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/ledger/[id]/': RouteRecordInfo<'/ledger/[id]/', '/ledger/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/ledger/[id]/itinerary/': RouteRecordInfo<'/ledger/[id]/itinerary/', '/ledger/:id/itinerary', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/ledger/[id]/split/': RouteRecordInfo<'/ledger/[id]/split/', '/ledger/:id/split', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/ledger/create/': RouteRecordInfo<'/ledger/create/', '/ledger/create', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/my': RouteRecordInfo<'/my', '/my', Record<never, never>, Record<never, never>>,
    '/register': RouteRecordInfo<'/register', '/register', Record<never, never>, Record<never, never>>,
    '/travel/': RouteRecordInfo<'/travel/', '/travel', Record<never, never>, Record<never, never>>,
  }
}
